### ISSUE TITLE
Running into NameError running script.

### ISSUE THREAD

**Issue by shakoin** [Mr-Robot-ops/pihole-regex#1]
Whenever I run the install command

curl -sSl https://raw.githubusercontent.com/mr-robot-ops/pihole-regex/master/install.py | sudo python3

I get the following error back.

[i] Root user detected
[i] Pi-hole path exists
[i] DB detected
[i] Fetching: https://raw.githubusercontent.com/mr-robot-ops/pihole-regex/master/regex.list
[i] 1691 regexps collected from https://raw.githubusercontent.com/mr-robot-ops/pihole-regex/master/regex.list
[i] Connecting to /etc/pihole/gravity.db
[i] Adding / updating regexps in the DB
Traceback (most recent call last):
  File "<stdin>", line 127, in <module>
NameError: name 'regexps_mrrobotops_local' is not defined

Not sure if the value isnt set correctly within the script at least from what is being reported back.

Seems The regex are being added though.

**Comment by Mr-Robot-ops** [comment]
Thanks for your report.

I've been studying the script with your help. It was out of date because of the pi-hole 5 update. 

Everything should be working normally again.

**Comment by shakoin** [comment]
So just ran it it worked thanks for your help.
